### ISSUE TITLE
bgImageId is not used to calculate price in function calcMintPrice

### ISSUE THREAD

**Issue by NicolasMahe** [QuiverCommunity/quiver-contracts#10]
The variable `bgImageId` is declared as parameter but not used to calculate price in function calcMintPrice.

https://github.com/QuiverCommunity/quiver-contracts/blob/c2283c1fcf0ef2bb312d94c22e54af5e43a2269c/contracts/QNFT/QNFTSettings.sol#L252-L295

I don't know if `bgImageId` must be used to calculate the price. If yes, there is a bug

@gopherquiv can you confirm

**Comment by gopherquiv** [comment]
background image is free. And the price is zero, confirmed.

**Comment by NicolasMahe** [comment]
ok very good. closing this issue
