### ISSUE TITLE
Automatically delete head branches

### ISSUE THREAD

**Issue by NicolasMahe** [QuiverCommunity/quiver-contracts#15]
Please activate the "Automatically delete head branches" option in the setting of this repo: https://github.com/QuiverCommunity/quiver-contracts/settings

<img width="938" alt="Screenshot 2021-05-19 at 10 48 20" src="https://user-images.githubusercontent.com/5823445/118753704-bc110c00-b88f-11eb-8665-e25c3b20fede.png">

**Comment by gopherquiv** [comment]
Done
