### ISSUE TITLE
Deploy smart contracts on testnet with data

### ISSUE THREAD

**Issue by NicolasMahe** [QuiverCommunity/quiver-contracts#16]
Could you guys deploy the smart contract on testnet with data.

I need data in the QNFTSettings smart contract to be able to mint with from the QNFT.

You can also create a new markdown file to specify all useful info about those deployment: address, who is manager, what data have been added, etc...

**Comment by gopherquiv** [comment]
I thought it's done on ropsten, @icrabbiter  can you give answer to @NicolasMahe

**Comment by icrabbiter** [comment]
Yeah, the previous version was deployed on ropsten.
You can find the address here - https://github.com/QuiverCommunity/quiver-contracts/blob/master/scripts/settings.json

**Comment by NicolasMahe** [comment]
perfect! thanks
