### ISSUE TITLE
Issue with the withdraw mechanism

### ISSUE THREAD

**Issue by antho1404** [QuiverCommunity/quiver-contracts#17]
The goal for the user to have this NFT is to sell it for the value it represents, here the QSTK token locked and attached to the NFT, or simply cash out their QSTK.

It is totally valid to guess that the user will mint/buy an emotional NFT and then sell it for the position it represents (the token locked).

This behavior is really good and should be encouraged, but the current implementation has issues that can quickly turn this behavior into scams.

Currently, the owner can withdraw the QSTK at the end of the lock period without checking that the NFT is actually in sale on platforms like OpenSea.

Here is the possible issue:

- Alice has an NFT with a lock worse of $10k of QSTK that is about to end or has ended
- Alice sell the NFT on a marketplace for bidding (e.g.: OpenSea)
- Bob put an offer for the NFT of $10k+ (as the NFT has a lock of $10k, it is worse **at least** $10k)
- Alice withdraw the $10k
- Alice accepts the sale for $10k+
- Bob paid $10k+ and has an NFT that is now worse $0

Your NFT is now associated with a scam, and users will not want to take the risk to buy a QSTK position if it is not guaranteed that they can redeem the locked amount.

One solution for this problem is to forbid NFT owners to withdraw their tokens if they are selling at the same time, but this is unfortunately not possible.

The common solution is to allow the token **withdrawal only when the NFT is redeemed** (have a look at Unisocks, for example). This means that the user will burn its NFT and lose ownership of it, and, as a result, receive the locked QSTK. Of course, this burn/redeem should only be possible after the lock period.

**Comment by NicolasMahe** [comment]
> user will burn its NFT and lose ownership of it, and, as a result, receive the locked QSTK. Of course, this burn/redeem should only be possible after the lock period.

I like this concept: redeeming the NFT to access the underlying assets.

**Comment by gopherquiv** [comment]
* If an NFT is burnt that is with random ID, how do we iterate global NFTs?
* If they redeem QSTK tokens, they would lose nice NFT, should we probably just change the ID of NFT when redeeming so that it can't be sold on marketplaces?
* How IDs management should work in this case?

**Comment by gopherquiv** [comment]
I discussed with @icrabbiter 
Two options
* we give this as a risk to the buyer. Emotional NFT will be expensive for its character, not QSTK put in it.
NFT purchaser's buy request should contain the risk of he/she will not get QSTK in it if the seller withdraws it.
* we block nft transfer if QSTK is withdrawn. The user will have permanent ownership of the NFT and use it permanently.

**Comment by NicolasMahe** [comment]
> we block nft transfer if QSTK is withdrawn. The user will have permanent ownership of the NFT and use it permanently. It will make user to select one of two options, keep NFT transferrable for NFT price grow. NFT to be not transferrable by taking out QSTK tokens in it. But he can still use the NFT as it's his/her owned one even though not transferrable. Maybe governance can make it transferrable ?

I think blocking the transfer actually makes more sense than burning it.
Burning the NFT is maybe too much because all the NFT's data will be lost.

If the NFT only "locked" (cannot be transferred, upgraded, or anything that change it), anyone can still see the NFT's info forever.

We could call this feature "redeem" NFT for QSTK and then add a dedicated page on the DApp to show all redeemed NFTs.

**Comment by gopherquiv** [comment]
We will make transfer possibility by admin (governance) when all users want to make NFTs transferrable even though QSTK is unlocked.
