### ISSUE TITLE
Metadata implementation

### ISSUE THREAD

**Issue by NicolasMahe** [QuiverCommunity/quiver-contracts#2]
Related to https://github.com/Quiver-Protocol/emotional-nft-dapp/discussions/26.

Adding a [`metaUrl`](https://github.com/QuiverCommunity/quiver-contracts/blob/6a9742d1390fe73396045f13c4e04782e21f0984/contracts/interface/structs.sol#L22) to each token is not the way to implement the metadata standard of ERC721.

With the OpenZeppelin implementation, the function `_baseURI` defined in `ERC721Upgradeable` must be override to return the baseURI. Example:

```solidity
function _baseURI() internal view virtual override returns (string memory) {
    return _baseTokenURI;
}
```
> Example from [`ERC721PresetMinterPauserAutoIdUpgradeable`](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/bd5d681b514c9fd3e1da28e0a6c63ead9369192d/contracts/token/ERC721/presets/ERC721PresetMinterPauserAutoIdUpgradeable.sol#L71-L73)

According to this example, the smart contract needs to save the variable `_baseTokenURI` in its state.
It value should be set in `initialize` function
A function to change its value added to allow the `manager` to change the API's http URL.

With the function `_baseURI` implemented and the value (for example) `https://quiverprotocol.com/` set in `_baseTokenURI`, the public function [`tokenURI`](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/token/ERC721/ERC721Upgradeable.sol#L98) will return something like `https://quiverprotocol.com/1` for the first token.

Fetching this URL will return the metadata payload that is required by the NFT marketplace.
The server responsible to return the metadata will be integrated directly into https://github.com/Quiver-Protocol/emotional-nft-dapp

**Comment by gopherquiv** [comment]
Ok it would be good to be added.
