### ISSUE TITLE
set a maxSupply per character

### ISSUE THREAD

**Issue by NicolasMahe** [QuiverCommunity/quiver-contracts#24]
originally posted in https://github.com/QuiverCommunity/quiver-contracts/pull/22#discussion_r635716582

don't you want to set the maxSupply per character?
eg: bull has maxSupply of 50, fish has maxSupply of 150
characters have specific prices, it would make sense to have different supply to justify the different prices

**Comment by gopherquiv** [comment]
Ok, we need to implement different supply per character.
