### ISSUE TITLE
Rename token uniqueness id

### ISSUE THREAD

**Issue by NicolasMahe** [QuiverCommunity/quiver-contracts#3]
Small issue that will reduce a lot the confusion between token id and token "uniqueness" id.

The OpenZeppelin implementation already use the term `id` for the token. Let's NOT reuse this term in the context of token.

Example of line that is super confusing:
https://github.com/QuiverCommunity/quiver-contracts/blob/6a9742d1390fe73396045f13c4e04782e21f0984/contracts/QNFT/QNFT.sol#L523

I suggest to rename the token "uniqueness" id to [hash](https://en.wikipedia.org/wiki/Hash_function):

```diff
-    mapping(uint256 => uint256) private nftIds;
+    // Mapping from token hash to token id
+    mapping(uint256 => uint256) private nftHashes;
```

Also if you want to respect the [OpenZeppelin code-style](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/bd5d681b514c9fd3e1da28e0a6c63ead9369192d/contracts/token/ERC721/ERC721Upgradeable.sol#L29-L30), I suggest:

```solidity
   // Mapping from token hash to token id
   mapping(uint256 => uint256) private _hashes;
```

This modif must be propagated to related functions' name:
```diff
-    function _getNftId(
+    function _getTokenHash(
```
```diff
-    function _setNftId(
+    function _setTokenHash(
```

Lastly, the function `nftMinted` could directly return the token id instead of a boolean. It will be easier for the DApp to fetch info related to an existing nft.This will also require to rename the function.

```diff
-    function nftMinted(
+    function tokenId(
         uint256 _imageId,
         uint256 _bgImageId,
         uint256 _favCoinId,
         uint256 _lockDuration
-    ) public view returns (bool) {
-        return
-            _getNftId(_imageId, _bgImageId, _favCoinId, _lockDuration) !=
-            uint256(0);
+    ) public view returns (uint256) {
+        return _getNftId(_imageId, _bgImageId, _favCoinId, _lockDuration);
     }
```

**Comment by gopherquiv** [comment]
Is it normal approach? How would we navigate around whole nfts if ids are not incrementing gradually? Should keep all of those on backend? Btw what storage should we use to store all the nft ids?

**Comment by NicolasMahe** [comment]
> Is it normal approach?

Yes it is. Hash functions are the classic way to create a unique short string from arbitrary data. It's exactly what IPFS is doing with its hashes.

> How would we navigate around whole nfts if ids are not incrementing gradually?

The smart contract still uses the incremented number (`nftCount` in the codebase) as token id. This issue is NOT about this.

The goal of this issue is to remove the confusion between 2 distinct systems: ids and hashes.

Currently, the hashes are also named ids. I'm suggesting to fix this.

> Should keep all of those on backend? Btw what storage should we use to store all the nft ids?

The token ids are saved by the following state variable implemented by the underlying [ERC721Upgradeable smart contract](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/bd5d681b514c9fd3e1da28e0a6c63ead9369192d/contracts/token/ERC721/ERC721Upgradeable.sol#L29-L30) from OpenZeppelin:
```solidity
    // Mapping from token ID to owner address
    mapping (uint256 => address) private _owners;
```

No need to save them in the backend. They can be fetch from the blockchain.

**Comment by gopherquiv** [comment]
@icrabbiter can you handle this comment from @NicolasMahe ? Just find a suitable solution with him and you can both agree on this. I am not a contract expert. Just know how to read. :)
