### ISSUE TITLE
Upgraded NFTs keep the same id/hash

### ISSUE THREAD

**Issue by NicolasMahe** [QuiverCommunity/quiver-contracts#4]
The functions `upgradeNftImage`, `upgradeNftBackground` and `upgradeNftCoin` does not change the id/hash of the NFT that is being upgraded.

Example:
If somebody mints token with image A, then upgrades to image B, then somebody can mint the same NFT with image B.
But NOBODY can mint the token with image A.

Is it the expected flow?

I think the upgrade functions should unset the current NFT's id/hash, calculate the new one, and save it.

**Comment by gopherquiv** [comment]
Thanks for the report. I will let our dev to know.
