### ISSUE TITLE
limit access to updateBaseUrl function

### ISSUE THREAD

**Issue by NicolasMahe** [QuiverCommunity/quiver-contracts#8]
Related to https://github.com/QuiverCommunity/quiver-contracts/pull/5#discussion_r634015174

The function `updateBaseUrl` is currently executable by anyone.
It must be limited to `onlyManager` otherwise anyone could change the base url and break the metadata api system.

https://github.com/QuiverCommunity/quiver-contracts/blob/c2283c1fcf0ef2bb312d94c22e54af5e43a2269c/contracts/QNFT/QNFT.sol#L146-L148

```diff
-    function updateBaseUrl(string memory _quiverBaseUrl) external {
+    function updateBaseUrl(string memory _quiverBaseUrl) external onlyManager {
         _baseTokenURI = _quiverBaseUrl;
     }
```

**Comment by gopherquiv** [comment]
@icrabbiter can you make quick fix on this?
